### ISSUE TITLE
Standardize Sarya Marid names with Regex expression

### ISSUE THREAD

**Issue by mj-cycls** [Cycls/Sarya#13]
Come up with regex that validates Marid names and share it with developer portal

A few points:
1. minimum length, is this needed? 
2. maximum length?
3. `-` instead of `_`
4. The Regex expression for validation

**Comment by kk-cycls** [comment]
in user switching (using @ in chat) or in creating new marid's handler, we will do the following: 
- if any letter is capital we will take the lower case  of the same letter 
- if we find `_` in we will turn it to `-` 

for example if a user switched to `@Handler_2022` we will look for the marid with a handler `@handler-2022`
